#!/usr/bin/env python3
"""infra/searxng/setup.py — one-command SearXNG (private local web search) setup.

WHAT / WHY / HOW
  SearXNG is a self-hosted metasearch engine (https://github.com/searxng/searxng).
  This script brings up a PRIVATE instance on http://127.0.0.1:8080 so ANY coding
  agent (or script) has free, private web search with a JSON API — no API key.

  WHY you want it: the job-hunt agent uses web search to find portal-only roles
  ("<product> QA SDET Bengaluru greenhouse/lever/icims"). A local instance keeps
  searches private and free.

WHEN to run it: once, during `python3 hub.py install`, or anytime:
      python3 infra/searxng/setup.py

WHAT it does:
  1. writes infra/searxng/.env (SEARXNG_BASE_URL + a random SEARXNG_SECRET)
  2. writes infra/searxng/core-config/settings.yml (enables the JSON API)
  3. starts the containers with `docker compose up -d`
  4. waits and verifies:  curl "http://127.0.0.1:8080/search?q=test&format=json"
"""
import json
import os
import secrets
import shutil
import socket
import subprocess
import sys
import time
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ENV = os.path.join(HERE, ".env")
ENV_EXAMPLE = os.path.join(HERE, ".env.example")
SETTINGS = os.path.join(HERE, "core-config", "settings.yml")
BASE_URL = "http://127.0.0.1:8080"


def log(m):
    print(f"[searxng] {m}", flush=True)


def run(cmd, cwd=HERE):
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def port_open(port=8080):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.5)
        return s.connect_ex(("127.0.0.1", port)) == 0


def have_docker():
    return bool(shutil.which("docker"))


def have_compose():
    if shutil.which("docker"):
        r = run(["docker", "compose", "version"])
        if r.returncode == 0:
            return True
    return bool(shutil.which("docker-compose"))


def compose_cmd():
    if shutil.which("docker"):
        r = run(["docker", "compose", "version"])
        if r.returncode == 0:
            return ["docker", "compose"]
    if shutil.which("docker-compose"):
        return ["docker-compose"]
    return None


def write_env(base=HERE):
    env = os.path.join(base, ".env")
    if os.path.exists(env):
        log(f"{os.path.relpath(env)} already exists — keeping it")
        return env
    secret = secrets.token_hex(24)
    content = []
    env_example = os.path.join(base, ".env.example")
    if os.path.exists(env_example):
        content.append(open(env_example).read().rstrip())
    else:
        content.append("# generated by setup.py")
        content.append("SEARXNG_VERSION=latest")
        content.append("SEARXNG_HOST=127.0.0.1")
        content.append("SEARXNG_PORT=8080")
    content.append(f"SEARXNG_BASE_URL={BASE_URL}")
    content.append(f"SEARXNG_SECRET={secret}")
    with open(env, "w") as f:
        f.write("\n".join(content) + "\n")
    log(f"wrote {os.path.relpath(env)} (random secret)")
    return env


def write_settings(base=HERE):
    settings_path = os.path.join(base, "core-config", "settings.yml")
    if os.path.exists(settings_path):
        log(f"{os.path.relpath(settings_path)} already exists — keeping it")
        return settings_path
    os.makedirs(os.path.dirname(settings_path), exist_ok=True)
    secret = secrets.token_hex(24)
    settings = (
        "use_default_settings: true\n"
        "server:\n"
        f"  secret_key: \"{secret}\"\n"
        "  limiter: false\n"
        "  public_instance: false\n"
        "search:\n"
        "  formats:\n"
        "    - html\n"
        "    - json\n"
    )
    with open(settings_path, "w") as f:
        f.write(settings)
    log(f"wrote {os.path.relpath(settings_path)} (JSON API enabled)")
    return settings_path


def verify_json(timeout=90):
    """Poll the JSON search API until it answers (container may take a while)."""
    url = f"{BASE_URL}/search?q=test&format=json"
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            req = urllib.request.Request(url, headers={"Accept": "application/json"})
            with urllib.request.urlopen(req, timeout=5) as resp:
                data = resp.read()
                if resp.status == 200 and data.strip():
                    d = json.loads(data)
                    return True, len(d.get("results", []))
        except Exception:
            pass
        time.sleep(3)
    return False, 0


def main():
    print("=" * 68)
    print("  SearXNG — private local web search (https://github.com/searxng/searxng)")
    print("=" * 68)

    if not have_docker():
        print("  ❌ docker not found. Install Docker first:")
        print("     macOS:  brew install --cask docker")
        print("     Linux:  sudo apt-get install -y docker.io docker-compose-v2")
        print("     Windows: winget install Docker.DockerDesktop")
        print("  Then re-run:  python3 infra/searxng/setup.py")
        return 1

    if port_open():
        log("port 8080 is already in use — SearXNG may already be running")
        ok, n = verify_json(timeout=5)
        if ok:
            print(f"  ✅ SearXNG already up — JSON API returns results ({n} on a test query)")
            print(f"  Search URL: {BASE_URL}/search?q=...&format=json")
            return 0

    write_env()
    write_settings()

    cc = compose_cmd()
    if not cc:
        print("  ❌ docker compose not available — install docker-compose-v2")
        return 1

    log("starting containers…")
    r = run(cc + ["up", "-d"])
    if r.returncode != 0:
        print("  ❌ docker compose up failed:")
        print(r.stdout[-800:], r.stderr[-800:])
        return 1

    log("waiting for the JSON API to come up…")
    ok, n = verify_json()
    if ok:
        print(f"  ✅ SearXNG is UP — test query returned {n} results")
        print(f"  Search URL: {BASE_URL}/search?q=...&format=json")
        print(f"  pi web-search config: ~/.pi/web-search.json → searxngBaseUrl: {BASE_URL}")
        print(f"  Docs: https://github.com/searxng/searxng")
        return 0
    print("  ⚠️  container started but JSON API not answering yet.")
    print("  Check: docker compose ps / logs (run from infra/searxng):")
    print("     cd infra/searxng && docker compose ps && docker compose logs -f core")
    return 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(130)
